### ISSUE TITLE
Wrong styling of rust code due to error in macro

### ISSUE THREAD

**Issue by nbigaouette-eai** [miqid/atom-language-rust#12]
Styling `tensorflow-sys/build.rs` from the [tensorflow/rust](https://github.com/tensorflow/rust) repository (commit [cb891b9349006a86742c0d017f1ca380c225c8be](https://github.com/tensorflow/rust/blob/cb891b9349006a86742c0d017f1ca380c225c8be/tensorflow-sys/build.rs)) fails at line 36, making the remaining of the file as if it was a string.

See the screenshot:

![image](https://cloud.githubusercontent.com/assets/25907218/23800208/6a46b92e-0579-11e7-9bc4-ee055407033e.png)

Using atom-language-rust 0.12.0 on Atom 1.14.3 with default theme.

Thank you for your work!

**Comment by miqid** [comment]
Thanks for reporting this.

I've updated the grammar to reflect the fact that Rust lets you enclose macro definitions with brackets—I actually wasn't aware of this allowance, so it's definitely great to know. The fix is in the next release ([0.12.1](https://github.com/miqid/atom-language-rust/releases/tag/0.12.1)). Simply upgrade this package to get it, and you shouldn't have problems with the snippet in the screenshot you've included. 😄
