### ISSUE TITLE
«Toggle comments» function is broken

### ISSUE THREAD

**Issue by ariasuni** [miqid/atom-language-rust#3]
When I use the «Toggle comments» function of Atom while having atom-language-rust actived, code is being put between `//|/\*` and `*/`. It should use either `//` like language-rust, or `/*` and `*/` like when neither is activated.

**Comment by miqid** [comment]
Thanks for pointing out this out—I haven't found myself using this key binding, so it has gone under the radar for me. 

It is trivial enough to fix the comment toggling behaviour so that any lines with at least one character selected will be prepended with line comment tokens. I will do this for the next release. However, it appears that Atom itself doesn't have great support for toggling multi-line commenting, particularly when user text selection does not start or end at the beginning or end of lines respectively. You could raise this on the main Atom repository if you'd like to see the feature.

On a bit of a related note, I'm aware that comment highlighting is broken in some areas (i.e. inside function definitions) and I endeavour to resolve these as soon as possible too.

**Comment by ariasuni** [comment]
Nice. :) Concerning Atom itself, I only recently started using it so I’m not yet requesting new features or behavior changes, the current behavior don’t bother me.

**Comment by miqid** [comment]
@ariasuni, this issue should now be fixed in version [0.6.0](https://github.com/miqid/atom-language-rust/releases/tag/0.6.0).

If you still have problems with this shortcut, please reopen this issue. Thanks again.

**Comment by ariasuni** [comment]
Seems to work great. Thank you. :)
